.TH "BST" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BST \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinsert\fP (int data)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBNode\fP< int > *r)"
.br
.ti -1c
.RI "bool \fBhas\fP (int data, \fBNode\fP< int > *startingNode)"
.br
.ti -1c
.RI "\fBNode\fP< int > * \fBseek\fP (int data, \fBNode\fP< int > *startingNode)"
.br
.ti -1c
.RI "void \fBsweep\fP (\fBNode\fP< int > *a)"
.br
.ti -1c
.RI "int \fBcountNodes\fP (\fBNode\fP< int > *a)"
.br
.ti -1c
.RI "bool \fBisLeaf\fP (\fBNode\fP< int > *a)"
.br
.ti -1c
.RI "bool \fBisEmpty\fP ()"
.br
.ti -1c
.RI "\fBNode\fP< int > * \fBgetRoot\fP ()"
.br
.ti -1c
.RI "int \fBgetHeight\fP (\fBNode\fP< int > *a)"
.br
.ti -1c
.RI "int \fBgetTreeHeight\fP (\fBNode\fP< int > *a)"
.br
.ti -1c
.RI "\fBNode\fP< int > * \fBfindLeaf\fP (int data, \fBNode\fP< int > *a)"
.br
.ti -1c
.RI "void \fBprint\fP (\fBNode\fP< int > *a)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file bst\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
