.TH "test/Students/list.h" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/Students/list.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <node\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBList< T >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
