.TH "test/Students/mainwindow.cpp" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/Students/mainwindow.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
