.TH "MainWindow" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *parent=0)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 16 of file mainwindow\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
