.TH "qt_meta_stringdata_MainWindow_t" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_MainWindow_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QByteArrayData \fBdata\fP [6]"
.br
.ti -1c
.RI "char \fBstringdata\fP [125]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 21 of file moc_mainwindow\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
