.TH "rbtn::Node< T >" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rbtn::Node< T > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNode\fP (T content, \fBNode\fP< T > *init)"
.br
.ti -1c
.RI "T \fBgetData\fP ()"
.br
.ti -1c
.RI "\fBNode\fP< T > * \fBgetLeft\fP ()"
.br
.ti -1c
.RI "\fBNode\fP< T > * \fBgetRight\fP ()"
.br
.ti -1c
.RI "\fBNode\fP< T > * \fBgetParent\fP ()"
.br
.ti -1c
.RI "int \fBgetHeight\fP ()"
.br
.ti -1c
.RI "int \fBgetColor\fP ()"
.br
.ti -1c
.RI "void \fBsetLeft\fP (\fBNode\fP< T > *ptr)"
.br
.ti -1c
.RI "void \fBsetRight\fP (\fBNode\fP< T > *ptr)"
.br
.ti -1c
.RI "void \fBsetParent\fP (\fBNode\fP< T > *ptr)"
.br
.ti -1c
.RI "void \fBsetHeight\fP (int h)"
.br
.ti -1c
.RI "void \fBsetColor\fP (int c)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class T>class rbtn::Node< T >"

.PP
Definition at line 105 of file Node\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
