.TH "test/Students/student.h" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test/Students/student.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <QString>\fP
.br
\fC#include 'list\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStudent\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
