.TH "Student" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Student \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStudent\fP (int id, QString name, double first, double second, double final)"
.br
.ti -1c
.RI "int \fBgetId\fP ()"
.br
.ti -1c
.RI "QString \fBgetName\fP ()"
.br
.ti -1c
.RI "double \fBgetNote1\fP ()"
.br
.ti -1c
.RI "double \fBgetNote2\fP ()"
.br
.ti -1c
.RI "double \fBgetGrade\fP ()"
.br
.ti -1c
.RI "void \fBsetId\fP (int)"
.br
.ti -1c
.RI "void \fBsetName\fP (QString)"
.br
.ti -1c
.RI "void \fBsetNote1\fP (double first)"
.br
.ti -1c
.RI "void \fBsetNote2\fP (double second)"
.br
.ti -1c
.RI "void \fBsetGrade\fP (double final)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file student\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
