.TH "tracker" 3 "Fri May 1 2015" "DataStructures" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tracker \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcost\fP"
.br
.ti -1c
.RI "string \fBindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 19 of file Dijkstra\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for DataStructures from the source code\&.
